# shellcheck shell=bash
# peststack — artifact generation (installer script + Dockerfile)
# Maintainer: Cognis Digital
#
# All emitters operate on the parsed PS_* arrays and write to stdout. The CLI
# is responsible for redirecting to an --out file. Generated installers are
# idempotent: each tool block guards on a presence check before installing.

if [ -n "${PESTSTACK_GENERATE_SOURCED:-}" ]; then
  return 0 2>/dev/null || true
fi
PESTSTACK_GENERATE_SOURCED=1

# Internal: emit the per-method install command(s) for record i, indented.
# Writes the *action* only; the idempotence guard wraps it in the caller.
_ps_emit_install_cmd() {
  local i="$1" indent="$2"
  local method="${PS_METHOD[i]}" pkg="${PS_PACKAGE[i]}" ver="${PS_VERSION[i]}"

  case "$method" in
    apt)
      if [ -n "$ver" ]; then
        printf '%sapt-get install -y --no-install-recommends "%s=%s"\n' "$indent" "$pkg" "$ver"
      else
        printf '%sapt-get install -y --no-install-recommends "%s"\n' "$indent" "$pkg"
      fi
      ;;
    pip)
      if [ -n "$ver" ]; then
        printf '%spip3 install --no-cache-dir "%s==%s"\n' "$indent" "$pkg" "$ver"
      else
        printf '%spip3 install --no-cache-dir "%s"\n' "$indent" "$pkg"
      fi
      ;;
    go)
      if [ -n "$ver" ]; then
        printf '%sgo install "%s@%s"\n' "$indent" "$pkg" "$ver"
      else
        printf '%sgo install "%s@latest"\n' "$indent" "$pkg"
      fi
      ;;
    git)
      printf '%srm -rf "%s/%s"\n' "$indent" "\$PESTSTACK_SRC" "${PS_NAME[i]}"
      if [ -n "$ver" ]; then
        printf '%sgit clone --depth 1 --branch "%s" "%s" "%s/%s"\n' \
          "$indent" "$ver" "$pkg" "\$PESTSTACK_SRC" "${PS_NAME[i]}"
      else
        printf '%sgit clone --depth 1 "%s" "%s/%s"\n' \
          "$indent" "$pkg" "\$PESTSTACK_SRC" "${PS_NAME[i]}"
      fi
      ;;
    *)
      printf '%s: "unsupported method %s"\n' "$indent" "$method"
      ;;
  esac
}

# Internal: emit the presence check expression for record i.
# Echoes a shell test command that returns 0 when the tool is already present.
_ps_emit_presence_check() {
  local i="$1"
  local method="${PS_METHOD[i]}" name="${PS_NAME[i]}" pkg="${PS_PACKAGE[i]}"
  case "$method" in
    apt|go)
      printf 'command -v "%s" >/dev/null 2>&1' "$name"
      ;;
    pip)
      # importable module check; falls back to console-script presence
      printf 'python3 -c "import %s" >/dev/null 2>&1 || command -v "%s" >/dev/null 2>&1' \
        "$pkg" "$name"
      ;;
    git)
      printf '[ -d "$PESTSTACK_SRC/%s/.git" ]' "$name"
      ;;
    *)
      printf 'false'
      ;;
  esac
}

# ps_generate_installer — emit an idempotent bash installer to stdout.
ps_generate_installer() {
  local i

  printf '#!/usr/bin/env bash\n'
  printf '# Generated by peststack %s — DO NOT EDIT BY HAND.\n' "$PESTSTACK_VERSION"
  printf '# Maintainer: %s\n' "$PESTSTACK_MAINTAINER"
  printf '#\n'
  ps_authorized_banner_commented
  printf '\n'
  printf 'set -euo pipefail\n\n'

  printf '# Root for git-cloned tools (override with PESTSTACK_SRC).\n'
  printf 'PESTSTACK_SRC="${PESTSTACK_SRC:-/opt/peststack/src}"\n'
  printf 'mkdir -p "$PESTSTACK_SRC"\n\n'

  # Refresh apt index once up front if any apt tool is present.
  for (( i=0; i<PS_RECORD_COUNT; i++ )); do
    if [ "${PS_METHOD[i]}" = "apt" ]; then
      printf 'if command -v apt-get >/dev/null 2>&1; then\n'
      printf '  apt-get update\n'
      printf 'fi\n\n'
      break
    fi
  done

  for (( i=0; i<PS_RECORD_COUNT; i++ )); do
    local name="${PS_NAME[i]}" cat="${PS_CATEGORY[i]}" method="${PS_METHOD[i]}"
    local ver="${PS_VERSION[i]}" desc="${PS_DESC[i]}"
    printf '# ---------------------------------------------------------------------------\n'
    printf '# %s  [category: %s] [method: %s]%s\n' \
      "$name" "$cat" "$method" "${ver:+ [version: $ver]}"
    [ -n "$desc" ] && printf '# %s\n' "$desc"
    printf '# ---------------------------------------------------------------------------\n'
    printf 'install_%s() {\n' "$(_ps_safe_fn "$name")"
    printf '  if %s; then\n' "$(_ps_emit_presence_check "$i")"
    printf '    echo "[peststack] %s already present — skipping"\n' "$name"
    printf '    return 0\n'
    printf '  fi\n'
    printf '  echo "[peststack] installing %s via %s"\n' "$name" "$method"
    _ps_emit_install_cmd "$i" "  "
    printf '}\n'
    printf 'install_%s\n\n' "$(_ps_safe_fn "$name")"
  done

  printf 'echo "[peststack] toolkit provisioning complete."\n'
}

# Internal: sanitize a tool name into a valid shell function suffix.
_ps_safe_fn() {
  local s="$1"
  printf '%s' "${s//[^A-Za-z0-9_]/_}"
}

# ps_generate_dockerfile — emit a reproducible Dockerfile to stdout.
ps_generate_dockerfile() {
  local i has_apt=0 has_pip=0 has_go=0 has_git=0

  for (( i=0; i<PS_RECORD_COUNT; i++ )); do
    case "${PS_METHOD[i]}" in
      apt) has_apt=1 ;;
      pip) has_pip=1 ;;
      go)  has_go=1 ;;
      git) has_git=1 ;;
    esac
  done

  printf '# Generated by peststack %s — reproducible toolkit image.\n' "$PESTSTACK_VERSION"
  printf '# Maintainer: %s\n' "$PESTSTACK_MAINTAINER"
  printf '#\n'
  ps_authorized_banner_commented
  printf '\n'
  printf 'FROM debian:stable-slim\n\n'
  printf 'ENV DEBIAN_FRONTEND=noninteractive \\\n'
  printf '    PESTSTACK_SRC=/opt/peststack/src\n\n'

  # Base prerequisites depending on which methods are present.
  printf 'RUN apt-get update \\\n'
  printf '    && apt-get install -y --no-install-recommends \\\n'
  printf '        ca-certificates'
  [ "$has_git" -eq 1 ] && printf ' git'
  [ "$has_pip" -eq 1 ] && printf ' python3 python3-pip'
  [ "$has_go" -eq 1 ]  && printf ' golang'
  printf ' \\\n'
  printf '    && rm -rf /var/lib/apt/lists/*\n\n'

  printf 'RUN mkdir -p "$PESTSTACK_SRC"\n\n'

  # apt tools batched into a single RUN for layer efficiency.
  if [ "$has_apt" -eq 1 ]; then
    printf 'RUN apt-get update \\\n'
    printf '    && apt-get install -y --no-install-recommends'
    for (( i=0; i<PS_RECORD_COUNT; i++ )); do
      [ "${PS_METHOD[i]}" = "apt" ] || continue
      if [ -n "${PS_VERSION[i]}" ]; then
        printf ' \\\n        %s=%s' "${PS_PACKAGE[i]}" "${PS_VERSION[i]}"
      else
        printf ' \\\n        %s' "${PS_PACKAGE[i]}"
      fi
    done
    printf ' \\\n'
    printf '    && rm -rf /var/lib/apt/lists/*\n\n'
  fi

  # Per-tool RUN lines for pip / go / git.
  for (( i=0; i<PS_RECORD_COUNT; i++ )); do
    local method="${PS_METHOD[i]}" name="${PS_NAME[i]}"
    local pkg="${PS_PACKAGE[i]}" ver="${PS_VERSION[i]}"
    case "$method" in
      pip)
        if [ -n "$ver" ]; then
          printf 'RUN pip3 install --no-cache-dir "%s==%s"   # %s\n' "$pkg" "$ver" "$name"
        else
          printf 'RUN pip3 install --no-cache-dir "%s"   # %s\n' "$pkg" "$name"
        fi
        ;;
      go)
        if [ -n "$ver" ]; then
          printf 'RUN go install "%s@%s"   # %s\n' "$pkg" "$ver" "$name"
        else
          printf 'RUN go install "%s@latest"   # %s\n' "$pkg" "$name"
        fi
        ;;
      git)
        if [ -n "$ver" ]; then
          printf 'RUN git clone --depth 1 --branch "%s" "%s" "$PESTSTACK_SRC/%s"\n' \
            "$ver" "$pkg" "$name"
        else
          printf 'RUN git clone --depth 1 "%s" "$PESTSTACK_SRC/%s"\n' "$pkg" "$name"
        fi
        ;;
    esac
  done

  printf '\n'
  printf 'WORKDIR /opt/peststack\n'
  printf 'CMD ["/bin/bash"]\n'
}
